/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "sysint/cy_sysint.h"
#include "ipc/cy_ipc_drv.h"
#include "ipc/cy_ipc_sema.h"
#include "ipc/cy_ipc_pipe.h"
#include "sysclk/cy_sysclk.h"
#include "wdt/cy_wdt.h"
#include "tcpwm/cy_tcpwm.h"
#include "tcpwm/cy_tcpwm_counter.h"
#include "tcpwm/cy_tcpwm_pwm.h"
#include "tcpwm/cy_tcpwm_quaddec.h"
#include "scb/cy_scb_common.h"
#include "scb/cy_scb_i2c.h"
#include "scb/cy_scb_ezi2c.h"
#include "scb/cy_scb_spi.h"
#include "scb/cy_scb_uart.h"
#include "efuse/cy_efuse.h"
#include "flash/cy_flash.h"
#include "gpio/cy_gpio.h"
#include "sysanalog/cy_sysanalog.h"
#include "syspm/cy_syspm.h"
#include "syslib/cy_syslib.h"
#include "trigmux/cy_trigmux.h"
#include "systick/cy_systick.h"
#include "profile/cy_profile.h"
#include "prot/cy_prot.h"
#include "lvd/cy_lvd.h"
#include "cyfitter_cfg.h"
#include "cyfitter_sysint_cfg.h"
#include "cydevice_trm.h"
#include "CyClk_PumpPeri.h"
#include "cyfitter.h"
#include "cyfitter_gpio.h"
#include "cyfitter_sysint.h"
#include "cydisabledsheets.h"
#include "LCD_INTERFACE.h"
#include "DISP_TICK_TIMER.h"
#include "I2C_MASTER.h"
#include "CLOCK_2.h"
#include "UART_KITPROG_USB.h"
#include "I2C_MASTER_SCBCLK.h"
#include "UART_KITPROG_USB_SCBCLK.h"

/*[]*/

