/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* DISP_TICK_ISR */
#define DISP_TICK_ISR__INTC_CORTEXM4_ASSIGNED 1
#define DISP_TICK_ISR__INTC_CORTEXM4_PRIORITY 7u
#define DISP_TICK_ISR__INTC_NUMBER 90u
#define DISP_TICK_ISR_INTC_CORTEXM4_ASSIGNED 1
#define DISP_TICK_ISR_INTC_CORTEXM4_PRIORITY 7u
#define DISP_TICK_ISR_INTC_NUMBER 90u

/* I2C_MASTER_SCB_IRQ */
#define I2C_MASTER_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_MASTER_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_MASTER_SCB_IRQ__INTC_NUMBER 47u
#define I2C_MASTER_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_MASTER_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_MASTER_SCB_IRQ_INTC_NUMBER 47u

/* UART_KITPROG_USB_SCB_IRQ */
#define UART_KITPROG_USB_SCB_IRQ__INTC_NUMBER 43u
#define UART_KITPROG_USB_SCB_IRQ_INTC_NUMBER 43u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
