/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "GraphicLCDIntf_1.h"
#include "Pin_0_aliases.h"
#include "Pin_0.h"
#include "Clock_1.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "Pin_4_aliases.h"
#include "Pin_4.h"
#include "Pin_5_aliases.h"
#include "Pin_5.h"
#include "Pin_6_aliases.h"
#include "Pin_6.h"
#include "Pin_7_aliases.h"
#include "Pin_7.h"
#include "Timer.h"
#include "Pin_9_aliases.h"
#include "Pin_9.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

