# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SeniorProject/Oscilloscope_Senior_Project/Verilog/DAB_Interface/DAB_Interface/DAB_Interface.srcs/sources_1/bd/BlockRam/ip/BlockRam_blk_mem_gen_0_0/BlockRam_blk_mem_gen_0_0.xci
# IP: The module: 'BlockRam_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SeniorProject/Oscilloscope_Senior_Project/Verilog/DAB_Interface/DAB_Interface/DAB_Interface.srcs/sources_1/bd/BlockRam/ip/BlockRam_blk_mem_gen_0_0/BlockRam_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlockRam_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/SeniorProject/Oscilloscope_Senior_Project/Verilog/DAB_Interface/DAB_Interface/DAB_Interface.srcs/sources_1/bd/BlockRam/ip/BlockRam_blk_mem_gen_0_0/BlockRam_blk_mem_gen_0_0.xci
# IP: The module: 'BlockRam_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SeniorProject/Oscilloscope_Senior_Project/Verilog/DAB_Interface/DAB_Interface/DAB_Interface.srcs/sources_1/bd/BlockRam/ip/BlockRam_blk_mem_gen_0_0/BlockRam_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlockRam_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
